name: setup-rust
description: setup rust and caching
inputs:
  coverage:
    description: "Install cargo-llvm-cov for coverage"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: dtolnay/rust-toolchain@1.91.0
      with:
        components: rustfmt, clippy, llvm-tools-preview

    - name: Set environment variables
      shell: bash
      run: |
        echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
        echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"

    - uses: swatinem/rust-cache@v2

    - uses: mozilla-actions/sccache-action@v0.0.9

    - name: Install cargo-llvm-cov
      if: inputs.coverage == 'true'
      shell: bash
      run: cargo install cargo-llvm-cov --locked
